# EnchantMore - Extending Beyond Enchanted Items...
# Original Plugin By mushroomhostage. Version 2.0 And After By DSH105
#
# The comments in this configuration file will automatically be removed the first time the server is closed or reloaded
# You can find the default configuration file (with comments included) here:
#
# If an EnchantMore combination is not listed below, default to enabled (true) or disabled (false)
defaultEnabled: true
#
# For diagnosis purposes; if true, prints expanded item id + enchantment id to the console and states what EnchantMore is doing.
verboseLogger: false
#
# If effects are disabled, send a message to players letting them know about it. Cooldown is configurable (ticks)
debugDisabledEffects: true
disableMsgCooldownTicks: 6000    # Default: 5 minutes (6000 ticks)
#
# Sends a permission message if the player doesn't have the require permission
usePermissions: true
sendPermissionMessage: true
useCooldown: false
permMsgCooldownTicks: 6000    # Default: 5 minutes (6000 ticks)
#
# Listen for player movement
# Required for Boots + Power and Boots + Flame but can be disabled for performance reasons.
moveListener: true

effects:
    Axe + Aqua Affinity:    # Slowness to the user
        enable: true
        durationTicksPerLevel: 100    # Duration in ticks (20 ticks per second) for the Slowness Potion to last.
        amplifier: 1    # Slowness Potion Amplifier (1 is slowness I, 2 is slowness II, etc)
    Axe + Flame:    # Auto-Smelt
        enable: true
    Axe + Power:    # Fell Tree by breaking 1 log
        enable: true
        extraTrunkWidthPerLevel: 1    # How far to chop around the tree
    Axe + Respiration:    # Generate Tree
        enable: true
    Boots + Feather Falling:    # Zero Fall Damage
        enable: true
        minLevel: 10    # Minimum enchantment level upon which the effect is enabled.
    Boots + Flame:    #Firewalker (Set ground on fire as you walk)
        enable: true
    Boots + Power:    # Witch's Broom (Sprint Flying)
        enable: true
        yVelocityPerLevel: 1.0
    Boots + Punch:    # Hover Jump (Double Tap Shift)
        enable: true
        yVelocityPerEnchLevel: 1.0
    Bow + Aqua Affinity:    # Freeze water and stun players
        enable: true
        freezeRangePerLevel: 1    # Range of blocks that are frozen from the target per enchantment level.
        stunRangePerLevel: 1    # Range of blocks that players can be stunned per enchantment level.
        stunDurationTicksPerLevel: 100    # Duration in ticks (20 ticks per second) players are stunned per enchantment level.
    Bow + Bane Of Arthropods:    # Poison players who are shot.
        enable: true
        poisonRangePerLevel: 1.0    # Range of blocks that players can be poisoned per enchantment level. Players within the range of the arrow landing will be poisoned.
        poisonDurationTicksPerLevel: 100    # Duration in ticks (20 ticks per second) that the poison effect lasts for.
    Bow + Efficiency:    # Instant Shoot (Rapid fire)
        enable: true
    Bow + Feather Falling:    # Teleport to the place you shoot.
        enable: true
        minLevelGrappleHook: 2    # Level needed to make an invisible ladder at teleport location.
        grappleHangOnTicks: 200    # Time to delay before removing temporary ladder (10 seconds default)
    Bow + Fire Aspect:    # Fire explosion
        enable: true
        powerPerLevel: 1.0
    Bow + Knockback:    # Pierce through blocks
        enable: true
    Bow + Looting:    # Steal Items
        enable: true
    Bow + Respiration:    # Stapled arrows (attach items adjacent in inventory)
        enable: true
        payloads: # payloads to allow attaching to arrows adjacent in inventory
            allowSpawnEgg: true         # payload of spawn egg spawns creatures
            allowDoubleArrow: true      # payload of arrow shoots the 2nd arrow
            allowSnowball: true         # payload of snowball throws it
            allowEgg: true              # payload of egg has chance to hatch chicken
            allowTNT: true              # payload of TNT ignites primed explosion
            allowWaterBucket: true      # payload of water bucket dumps water
            allowLavaBucket: true       # payload of lava bucket dumps lava
            allowSplashPotion: true     # payload of splash potion throws the potion
            allowBlock: true            # payload of block places the block
            allowItem: true             # payload of other item drops the item (if off, item is deleted)
    Bow + Sharpness:     # Increase arrow velocity
        enable: true
        velocityPerLevel: 2.0    # Multiplier for arrow velocity
    Bow + Silk Touch:    # Magnetic Arrows (transport nearby entities)
        enable: true
        allowProjectiles: true      # Allow transportation of projectiles
        allowLivingEntities: true   # Allow transportation of entities
    Bow + Smite:    # Lightning strikes the place the arrow lands at.
        enable: true
    Chestplate + Infinity:    # God mode
        enable: true
    Chestplate + Knockback:    # Reflect arrows
        enable: true
    Chestplate + Punch:    # Brass knuckles (More fist damage)
        enable: true
        damagePerLevel: 5    # The amount of damage targets take per enchantment level.
    Chestplate + Respiration:    # Fish mode (No damage from drowning)
        enable: true
    Chestplate + Sharpness:    # Reflect damage
        enable: true
    Chestplate + Silk Touch:    # Cactus protection
        enable: true
    Fishing Rod + Efficiency:    # Catch fish faster
        enable: true
    Fishing Rod + Fire Aspect:    # Set mobs and players on fire if you fish them.
        enable: true
    Fishing Rod + Flame:    # Catch cooked fish
        enable: true
    Fishing Rod + Fortune:    # Catch other items
        enable: true
    Fishing Rod + Looting:    # Catch extra fish
        enable: true
    Fishing Rod + Sharpness:    # Damage mobs and players if you fish them
        enable: true
        damagePerLevel: 10    # The amount of damage mobs or players take when hit by the fishing rod per enchantment level
    Fishing Rod + Silk Touch:    # Catch more reliably
        enable: true
    Fishing Rod + Smite:    # Strikes mobs or players that you hook with lightning
        enable: true
    Flint & Steel + Aqua Affinity:    # Vaporise water
        enable: true
        shape: square
        effect: smoke    # smoke, fire, ender, explosion
    Flint & Steel + Blast Protection:    # Cancel nearby creeper explosions
        enable: true
    Flint & Steel + Efficiency:    # Burn faster (Turns wood to leaves)
        enable: true
    Flint & Steel + Fire Aspect:    # Sets mobs on fire
        enable: true
    Flint & Steel + Fire Protection:    # Fire Resistance potion effect
        enable: true
    Flint & Steel + Punch:    # Cannon
        enable: true
        particleEffect: true
    Flint & Steel + Respiration:    # Smoke inhalation (confusion effect)
        enable: true
    Flint & Steel + Sharpness:    # Fiery explosion
        enable: true
        fireworkEffect: false    # Plays a firework effect
        fwCharacteristics: trail:white:aqua:small    # Separated by a colon: trail, flicker, small, large, creeper, star, burst, aqua, black, blue, fuchsia, gray, green, lime, maroon, navy, orange, olive, purple, red, silver, teal, white, yellow
    Flint & Steel + Silk Touch:    # Remote Detonation
        enable: true
    Flint & Steel + Smite:    # Strikes lightning.
        enable: true
    Helmet + Fire Aspect:    # Lava protection.
        enable: true
    Hoe + Aqua Affinity:    # Auto-Hydrate farmland.
        enable: true
    Hoe + Bane of Arthropods:    # Weather control (Left click for a storm, right click for sun)
        enable: true
    Hoe + Efficiency:    # Till a larger area
        enable: true
    Hoe + Fire Protection:    # Block And Entity Information
        enable: true
    Hoe + Fortune:    # Chance to drop seeds
        enable: true
        chanceDropSeeds: 2      # 1-in-N change to drop seeds
        dropRollMax: 4          # Roll random number up 0..N-1
        drops:
            '0': seeds
            #'0': '1290'         # RedPower2 Flax Seeds
            '1': seeds
            '2': melon_seeds
            '3': pumpkin_seeds
    Hoe + Knockback:    # Eat dirt (Right click to knock into ground)
        enable: true
        yPerLevel: 1.0
    Hoe + Power:    # Change time
        enable: true
    Hoe + Punch:    # Turns baby mobs into adults
        enable: true
    Hoe + Respiration:    # Quick-grow (Bonemeal)
        enable: true
    Hoe + Silk Touch:    # Collect farmland, crop block, pumpkin/melon stem, cake block, sugarcane block, netherwart block (preserving data)
        enable: true
    Leggings + Feather Falling:    # Surface (Triple tap shift)
        enable: true
    Leggings + Knockback:    # Tackle (More damage when sprinting)
        enable: true
        damagePerLevel: 5    # The amount of damage entities take when hit while sprinting.
    Leggings + Punch:    # Rocket pants (Double-tap shift)
        enable: true
    Pickaxe + Flame:    # Auto-smelt blocks you mine
        enable: true
    Pickaxe + Looting:    # Deconstruct (Reverse Crafting)
        enable: true
    Pickaxe + Power:    # Instant break blocks
        enable: true
        breakBedrock: false    # Boolean value - whether bedrock can be broken
    Pickaxe + Sharpness:    # Mine ore vein
        enable: true
        rangePerLevel: 5    # Radius mined per enchantment level
        ores:
            14;0: true
            15;0: true
            16;0: true
            21;0: true
            56;0: true
            73;0: true
            74;0: true
            129;0: true
            153;0: true
            # New ores added by mods (harmless to leave if block IDs not used)
            '125;0': true       # Metallurgy CopperVein
            '127;0': true       # Metallurgy TinVein
            '130;0': true       # Metallurgy IronVein
            '132;0': true       # Metallurgy ManganeseVein
            '134;0': true       # Metallurgy MithrilVein
            '138;0': true       # Metallurgy AdamantineVein
            '140;0': true       # Metallurgy ZincVein / RedPower2 RubyOre
            '140;1': true       # RedPower2 EmeraldOre
            '140;2': true       # RedPower2 SapphireOre
            '140;3': true       # RedPower2 SilverOre
            '140;4': true       # RedPower2 TinOre
            '140;5': true       # RedPower2 CopperOre
            '140;6': true       # RedPower2 TungstenOre
            '140;7': true       # RedPower2 NikoliteOre
            '143;0': true       # Metallurgy SilverVein
            '145;0': true       # Metallurgy GoldVein
            '146;0': true       # Metallurgy PlatinumVein
            '247;0': true       # IndustrialCraft2 BlockOreUran
            '248;0': true       # IndustrialCraft2 BlockOreTin
            '249;0': true       # IndustrialCraft2 BlockOreCopper
            '247;32766': true   # IndustrialCraft2 BlockOreUran
            '248;32766': true   # IndustrialCraft2 BlockOreTin
            '249;32766': true   # IndustrialCraft2 BlockOreCopper
    Pickaxe + Silk Touch:    # Harvest more blocks
        enable: true
        minLevel: 2    # Since vanilla already has Silk Touch I, higher levels are required.
        harvestIce: true
        sublimateIce: false             # Vaporise ice placed in The Nether (note: must be configured in diamond pickaxe section)
        harvestDoubleSlabs: true        # Instead of breaking into two slabs
        placeDoubleSlabs: true          # Preserve subtype on placement (wooden, stone, etc.)
        harvestSilverfishBlocks: true   # Instead of releasing the silverfish.
        placeSilverfishBlocks: true     # Preserve subtype on placement (stone, cobblestone, stone brick)
        minLevelCrystal: 3              # Minimum level to harvest endercrystals by right-clicking
        spawnEggCrystal: true           # Allow right-click spawn egg endercrystals to place
    Shears + Bane of Arthropods:    # Collect spider eyes
        enable: true
    Shears + Fortune:    # Harvest apples from trees
        enable: true
    Shears + Looting:    # More wool (random colours), feathers from chickens, leather from cows, saddles from saddled pigs
        enable: true
    Shears + Power:    # Hedge trimmer/builder; cut grass
        enable: true
        shape: square    # The shape that will be trimmed. Can be "square" or "sphere"
    Shears + Silk Touch:    # Collect cobweb and dead bush
        enable: true
    Shears + Smite:    # Gouge eyes (Blindness effect)
        enable: true
    Shovel + Flame:    # Auto-smelt
        enable: true
    Shovel + Power:    # Excavation (Dig large area, no drops)
        enable: true
    Shovel + Silk Touch:    # Harvest fallen snow, fire
        enable: true
        minLevel: 2    # Since vanilla already has Silk Touch I, higher levels are required
        capturePlayers: false    # Whether should drop non-functional 'player' spawn eggs
    Sword + Blast Protection:    # Shoot fireball (right click)
        enable: true
    Sword + Feather Falling:    # Launch victim (right click)
        enable: true
        yVelocityPerLevel: 0.5
    Sword + Fire Protection:    # Return to player when dropped in lava
        enable: true
    Sword + Fortune:    # Pick pocket (right click player)
        enable: true
        maxLevel: 10
    Sword + Infinity:    # Selective invisibility (right click player)
        enable: true
        durationPerLevelTicks: 40    # Duration in ticks (20 ticks per second) invisible from target
    Sword + Power:    # Strike lightning far away
        enable: true
        rangePerLevel: 100    # Number of blocks away lightning can be spawned
    Sword + Protection:    # Resistance when blocking
        enable: true
    Sword + Punch:    # Knock out of hand (right click player)
        enable: true
        maxLevel: 10
        uses: 30
    Sword + Respiration:    # Banhammer Bans players that you hit it with
        enable: true
        kickLevel: 1
        kickMessage: 'Kicked by a Sword with a Respiration Enchantment by %s'
        banLevel: 2
        banCommand: 'ban %s'
        banTicksPerLevel: 200    # Duration in ticks (20 ticks per second) target is banned for
        pardonCommand: 'pardon %s'
    Sword + Silk Touch:    # Capture (Right-click to drop entity as item)
        enable: true

# Canonical names of enchantments and their respective IDs
# See http://www.minecraftwiki.net/wiki/Enchanting#Enchantments
enchantmentIDs:
    Protection: 0
    Fire Protection: 1
    Feather Falling: 2
    Blast Protection: 3
    Projectile Protection: 4
    Respiration: 5
    Aqua Affinity: 6
    Thorns: 7
    Sharpness: 16
    Smite: 17
    Bane of Arthropods: 18
    Knockback: 19
    Fire Aspect: 20
    Looting: 21
    Efficiency: 32
    Silk Touch: 33
    Unbreaking: 34
    Fortune: 35
    Power: 48
    Punch: 49
    Flame: 50
    Infinity: 51

# Categories of items - used in 'effects' section above to expand the given items and also internally for category-specific item enchantments
items:
    Pickaxe:
    - diamond_pickaxe
    - gold_pickaxe
    - iron_pickaxe
    - stone_pickaxe
    - wood_pickaxe
    # Add your custom tools here (item IDs)... defaults from http://www.mcportcentral.co.za/
    # If these items don't exist, they'll never be accessed, so they are harmless on vanilla, but, if the IDs conflict or are different you can change/remove them.
    - '1051'    # PlasticCraft PPickaxe
    - '1281'    # RedPower2 RubyPickaxe
    - '1282'    # RedPower2 EmeraldPickaxe
    - '1283'    # RedPower2 SapphirePickaxe
    - '3714'    # Mo' Food and Crops ObsidianPick
    - '13261'   # Forestry Survivalist's Pickaxe
    - '21259'   # Metallurgy CopperPickaxe
    - '21273'   # Metallurgy BronzePickaxe
    - '21289'   # Metallurgy SteelPickaxe
    - '21301'   # Metallurgy MithrilPickaxe
    - '21313'   # Metallurgy OrichalcumPickaxe
    - '21325'   # Metallurgy AdamantinePickaxe
    - '30200'   # IndustrialCraft2 ToolBronzePickaxe
    Hoe:
    - diamond_hoe
    - gold_hoe 
    - iron_hoe
    - stone_hoe
    - wood_hoe
    - '1287'    # RedPower2 RubyHoe
    - '1288'    # RedPower2 EmeraldHoe
    - '1289'    # RedPower2 SapphireHoe
    - '3717'    # Mo' Food and Crops ObsidianHoe
    - '21262'   # Metallurgy CopperHoe
    - '21276'   # Metallurgy BronzeHoe
    - '21292'   # Metallurgy SteelHoe
    - '21304'   # Metallurgy MithrilHoe
    - '21328'   # Metallurgy AdamantineHoe
    - '21316'   # Metallurgy OrichalcumHoe
    - '30119'   # IndustrialCraft2 ToolHoe (electric)
    - '30196'   # IndustrialCraft2 ToolBronzeHoe
    Sword:
    - diamond_sword   
    - gold_sword
    - iron_sword
    - stone_sword
    - wood_sword
    - '1275'    # RedPower2 RubySword
    - '1276'    # RedPower2 EmeraldSword
    - '1277'    # RedPower2 SapphireSword
    - '3718'    # Mo' Food and Crops ObsidianSword
    - '21263'   # Metallurgy CopperSword
    - '21277'   # Metallurgy BronzeSword
    - '21293'   # Metallurgy SteelSword
    - '21305'   # Metallurgy MithrilSword
    - '21317'   # Metallurgy OrichalcumSword
    - '21329'   # Metallurgy AdamantineSword
    - '30148'   # IndustrialCraft2 NanoSaber Uncharged
    - '30149'   # IndustrialCraft2 NanoSaber Charged
    - '30198'   # IndustrialCraft2 ToolBronzeSword
    Shovel:
    - diamond_spade
    - gold_spade
    - iron_spade
    - stone_spade
    - wood_spade
    - '1050'    # PlasticCraft PShovel
    - '1279'    # RedPower2 EmeraldShovel
    - '1280'    # RedPower2 SapphireShovel
    - '1278'    # RedPower2 RubyShovel
    - '3715'    # Mo' Food and Crops ObsidianShovel
    - '13264'   # Forestry Survivalist's Shovel
    - '21260'   # Metallurgy CopperShovel
    - '21274'   # Metallurgy BronzeShovel
    - '21290'   # Metallurgy SteelShovel
    - '21302'   # Metallurgy MithrilShovel
    - '21314'   # Metallurgy OrichalcumShovel
    - '21326'   # Metallurgy AdamantineShovel
    Axe:
    - diamond_axe
    - gold_axe
    - iron_axe
    - stone_axe
    - wood_axe
    - '1052'    # PlasticCraft PAxe
    - '1284'    # RedPower2 RubyAxe
    - '1285'    # RedPower2 EmeraldAxe
    - '1286'    # RedPower2 SapphireAxe
    - '3716'    # Mo' Food and Crops ObsidianAxe
    - '21261'   # Metallurgy CopperAxe
    - '21275'   # Metallurgy BronzeAxe
    - '21291'   # Metallurgy SteelAxe
    - '21303'   # Metallurgy MithrilAxe
    - '21315'   # Metallurgy OrichalcumAxe
    - '21327'   # Metallurgy AdamantineAxe
    - '30199'   # IndustrialCraft2 ToolBronzeAxe
    # Farm-related block, either land or growing crops 
    Farmblock:
    - soil      # Farmland
    - crops     # Wheat TODO: update wiki, calls 'Wheat Seeds' though in-game 'Crops'
    - sugar_cane_block
    - cake_block
    - pumpkin_stem
    - melon_stem
    - nether_warts # Not the item, that is nether_stalk (confusingly)
    Excavatable:
    - dirt
    - grass
    - gravel
    - sand
    - soul_sand
    - netherrack
    WoodenBlock:
    - wood
    - wood_plate
    - wood_stairs
    - wooden_door
    - log
    - step;2            # wooden slab
    - double_step;2     # wooden double slab

    # Categories below only used for effects shortcuts
    # Normally, armor effect determined by *slot* not *type* - if other item is in slot, then it will trigger if defaultEffectEnabled, so I haven't listed custom items here
    Helmet:
    - chainmail_helmet
    - diamond_helmet
    - gold_helmet
    - iron_helmet
    - leather_helmet
    Chestplate:
    - chainmail_chestplate
    - diamond_chestplate
    - gold_chestplate
    - iron_chestplate
    - leather_chestplate
    Leggings:
    - chainmail_leggings
    - diamond_leggings
    - gold_leggings
    - iron_leggings
    - leather_leggings
    Boots:
    - chainmail_boots
    - diamond_boots
    - gold_boots
    - iron_boots
    - leather_boots