name: EnchantMore
main: com.github.dsh105.enchantmore.EnchantMore
version: ${project.version}
description: Enchanted hoes, enchanted fishing rods, enchanted shears and more!
softdepend: 
    - WorldGuard